filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/azureuser/logs/oauth-api-production/*-debug.log
    fields:
      index_name: oauth-api
      env: production
      level: debug

  - type: log
    enabled: true
    paths:
      - /home/azureuser/logs/oauth-api-test/*-debug.log
    fields:
      index_name: oauth-api
      env: test
      level: debug

output.logstash:
  hosts: ["hnmcorp-legacy-elk.koreacentral.cloudapp.azure.com:5000"]
